curl-get-5:
	curl --location --request GET 'http://localhost:1801/' &
	curl --location --request GET 'http://localhost:1801/' &
	curl --location --request GET 'http://localhost:1801/' &
	curl --location --request GET 'http://localhost:1801/' &
	curl --location --request GET 'http://localhost:1801/'

start-server:
	node index.js
